# - preserve exec flag on bl

name: Haskell CI
on:
  push:
    # tags:
    # - "*"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: olegtarasov/get-tag@v2
        id: tag
        with:
          tagRegex: "(.*)"
          tagRegexGroup: 1

      - uses: actions/setup-haskell@v1
        id: setup-haskell-cabal
        with:
          ghc-version: "8.10.3"
          cabal-version: "3.2"

      - run: cabal update
      - run: cabal freeze
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - run: cabal install --install-method=copy --overwrite-policy=always --installdir=.

      - if: matrix.os == 'ubuntu-latest'
        run: zip -9jq bl-${{ steps.tag.outputs.tag }}-x86_64-linux.zip bl $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/LICENSE

      - if: matrix.os == 'windows-latest'
        run: zip -9jq bl-${{ steps.tag.outputs.tag }}-x86_64-windows.zip bl.exe $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/LICENSE

      - uses: ncipollo/release-action@v1
        with:
          draft: true
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ci-cd-test
          allowUpdates: true
