# - create windows binary
# - zip binaries
# - add LICENSE and README.md to zips
# - preserve exec flag on bl

name: Haskell CI

on:
  push:
    # tags:
    # - "*"

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.10.3"
          cabal-version: "3.2"

      - name: Cache ~/.cabal/packages, ~/.cabal/store
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-8.10.3

      - name: Install dependencies
        run: cabal build --only-dependencies --enable-tests --enable-benchmarks

      - name: Build binary
        run: cabal install --install-method=copy --overwrite-policy=always --installdir=.

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          artifacts: "bl,bl.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ci-cd-test
